name: Build-Overlays

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

env:
  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  USER_NAME: ${{ secrets.USER_NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  SF_PWD: ${{ secrets.SF_PWD }}
  RELEASE_TYPE: 'canary'
  ENVIRONMENT_TYPE: ${{ secrets.ENVIRONMENT_TYPE }}
  PACKAGE_LIST_10: ${{ secrets.PACKAGE_LIST_10 }}
  PACKAGE_LIST_11: ${{ secrets.PACKAGE_LIST_11 }}
  
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: Setup SSH Keys and known_hosts 
         uses: webfactory/ssh-agent@v0.4.1
         with:
             ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
       - name: Environment Details and clean up
         run: |
          sudo apt-get install neofetch zipalign
          neofetch
          df -H
          ls
          ls
       - name: Installing Requirements
         run: |
          zipalign
          java -jar apktool_2.6.1.jar -version
          ls

